#!/usr/bin/env bash
# =========================================================================== #
# Description: Commit message hook to validate format.
# =========================================================================== #

die() {
	local error_desc="$1"
	printf "Aborting commit due to %s.\n" "$error_desc" >&2
	exit 1
}

commit_msg="$(<"$1")"

prefix_regexp="^b\([[:alnum:]-]+\):"
msg_regexp="${prefix_regexp} .+$"

if [[ -z "$commit_msg" ]]; then
	die "empty commit message"
elif [[ "$commit_msg" != b* ]]; then
	die "missing branch signifier"
elif [[ ! "$commit_msg" =~ $prefix_regexp ]]; then
	die "missing or invalid commit scope"
elif [[ ! "$commit_msg" =~ $msg_regexp ]]; then
	die "missing commit description"
fi
