#!/usr/bin/env bash
# =========================================================================== #
# Description: Commit message hook to validate format.
# =========================================================================== #

commit_msg="$(<"$1")"
scope_regexp="^\([[:alnum:]-]+\):"
msg_regexp="${scope_regexp} .+$"

printf "Checking commit message format...\n"

if [[ ! "$commit_msg" =~ $scope_regexp ]]; then
	printf "  Missing or invalid scope. Commit aborted.\n" >&2
	exit 1
elif [[ ! "$commit_msg" =~ $msg_regexp ]]; then
	printf "  Missing commit description. Commit aborted. \n" >&2
	exit 1
fi
