#!/usr/bin/env bash
# =========================================================================== #
# Description: Pre-commit hook for hot-plate.
# =========================================================================== #

die() {
	local msg="$1"
	printf "Commit aborted: %s\n" "$msg" >&2
	exit 1
}

make lint || die "'make lint' failed."
