#!/usr/bin/env bash
# =========================================================================== #
# Description: Pre-commit syntax check.
# =========================================================================== #

if ! make lint; then
	printf "'make lint' failed. Aborting commit.\n" >&2
	exit 1
fi

printf "\n"
