#!/usr/bin/env bash
# =========================================================================== #
# Description: Pre-commit linting.
# =========================================================================== #
set -euo pipefail

bash_scripts="$(
  git diff --staged --name-only --diff-filter=ACMR \
    -- '*.sh' 'bin/**' '.githooks/**'
)"

if [[ -n "$bash_scripts" ]]; then
  make lint BASH_SCRIPTS="${bash_scripts//$'\n'/ }"
fi
