name: PR - CI Pipeline
run-name: >-
  "CI for PR #${{ github.event.pull_request.number || '?' }}
  from ${{ github.head_ref || github.ref_name }}
  (${{ github.event.action || github.event_name }})"

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          severity: error
          ignore_paths: >-
            test/bats
            test/test_helper
