name: PR - CI Pipeline
run-name: >-
  CI for PR #${{ github.event.pull_request.number || 'N/A' }}
  from ${{ github.head_ref || github.ref_name }}
  (${{ github.event.action || github.event_name }})

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          submodules: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --yes shfmt shellcheck

      - name: Run Makefile check
        run: make check
