name: Push - Version Tag
run-name: >-
  "Push tag to ${{ github.event.repository.name }}/${{ github.ref_name }}"

on:
  push:
    branches: [main]

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Update version
        env:
          SCRIPT: "./.github/scripts/push-tag.sh"
          COMMIT: ${{ github.event.head_commit.message }}
        run: |
          chmod +x "$SCRIPT"
          "$SCRIPT" "$COMMIT"
