name: Push - Version Tag
run-name: Push tag to ${{ github.ref_name }} (${{ github.event_name }})

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      commit:
        description: "Commit message to use for dry run."
        type: string
        required: true

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  push-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Create and push version tag
        env:
          COMMIT: ${{ inputs.commit || github.event.head_commit.message }}
          EVENT_NAME: ${{ github.event_name }}
        run: |
          if [[ "$EVENT_NAME" == "workflow_dispatch" ]]; then
            ./.github/scripts/push-tag.sh --dry-run "$COMMIT"
          else
            ./.github/scripts/push-tag.sh "$COMMIT"
          fi
