name: Version
run-name: Version Bump for "${{ github.event.head_commit.message }}"

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Update version
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          chmod +x ./.github/scripts/version.sh
          ./.github/scripts/version.sh
